# Generated by Django 5.0 on 2023-12-08 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 13, 35, 18, 651163)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 8, 13, 35, 18, 651163)),
        ),
    ]
