# Generated by Django 5.0 on 2023-12-09 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_reports_order_date_alter_reports_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='category_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='category_name',
            field=models.CharField(default='deneme', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 11, 32, 19, 941313)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 11, 32, 19, 941313)),
        ),
    ]
