# Generated by Django 5.0 on 2023-12-09 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_reports_category_id_reports_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='category_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 1, 36, 89295)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 1, 36, 89295)),
        ),
    ]
