# Generated by Django 5.0 on 2023-12-09 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0004_alter_reports_category_id_alter_reports_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 9, 42, 917561))),
                ('device_id', models.BigIntegerField()),
                ('device_name', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 9, 42, 916561)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 9, 42, 916561)),
        ),
    ]
