# Generated by Django 5.0 on 2023-12-09 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0005_cashreports_alter_reports_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 23, 42, 610312)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 23, 42, 610312)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 23, 42, 610312)),
        ),
    ]
