# Generated by Django 5.0 on 2023-12-09 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0006_alter_cashreports_date_alter_reports_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 24, 8, 93897))),
                ('entry', models.BooleanField()),
                ('order_id', models.BigIntegerField()),
                ('battery', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cashreports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 24, 8, 93897)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 24, 8, 92897)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 14, 24, 8, 92897)),
        ),
    ]
