# Generated by Django 5.0 on 2023-12-09 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0007_batteryreports_alter_cashreports_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batteryreports',
            old_name='order_id',
            new_name='device_id',
        ),
        migrations.AlterField(
            model_name='batteryreports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 23, 44, 57, 46470)),
        ),
        migrations.AlterField(
            model_name='cashreports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 23, 44, 57, 46470)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 23, 44, 57, 46470)),
        ),
        migrations.AlterField(
            model_name='reports',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 23, 44, 57, 46470)),
        ),
    ]
