# Generated by Django 5.0 on 2023-12-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('battery', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_locked_date', models.DateField()),
                ('last_unlocked_date', models.DateField()),
            ],
        ),
    ]
