# Generated by Django 5.0 on 2023-12-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='total',
        ),
    ]
