# Generated by Django 5.0 on 2023-12-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_remove_devices_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='last_locked_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='devices',
            name='last_unlocked_date',
            field=models.DateTimeField(),
        ),
    ]
