# Generated by Django 5.0 on 2023-12-06 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Device.devices')),
            ],
        ),
    ]
