# Generated by Django 5.0 on 2023-12-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='payment_status',
        ),
    ]
