# Generated by Django 5.0 on 2023-12-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_remove_carts_payment_status'),
        ('Device', '0003_alter_devices_last_locked_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='Device.devices'),
        ),
    ]
