# Generated by Django 5.0 on 2023-12-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_orders_product'),
        ('Product', '0002_rename_product_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Product.products'),
        ),
    ]
